application: kurrik-slides
version: 1
runtime: python
api_version: 1

handlers:
- url: /html5-techtalk/static
  static_dir: html5-techtalk/static
  expiration: "1d"
  
- url: /html5-awesome/static
  static_dir: html5-awesome/static
  expiration: "1d"
  
- url: /static
  static_dir: static
  expiration: "1d"

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
       
- url: .*
  script: main.py
