application: html5apps-io2010
version: 1
runtime: python
api_version: 1

handlers:
- url: /static/fonts
  static_dir: static/fonts
  mime_type: font/opentype
  
- url: /static
  static_dir: static
  expiration: "1d"

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
       
- url: .*
  script: main.py
